environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.gradle

build_script:
  - gradlew.bat build

on_success:
  - keytool -keystore build\cacerts.jks -v -list -storepass changeit
